# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-6a7b41ec-1e90-47b0-83aa-b90fa60a1575";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."luks-6a7b41ec-1e90-47b0-83aa-b90fa60a1575".device = "/dev/disk/by-uuid/6a7b41ec-1e90-47b0-83aa-b90fa60a1575";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-6a7b41ec-1e90-47b0-83aa-b90fa60a1575";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/63A7-B720";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/data" =
    { device = "/dev/mapper/luks-b27c1e47-e98a-4b62-8b5e-9956cebb242b";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-b27c1e47-e98a-4b62-8b5e-9956cebb242b".device = "/dev/disk/by-uuid/b27c1e47-e98a-4b62-8b5e-9956cebb242b";

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
